export const sidebarStyles = {
  card: "w-full rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] shadow-sm overflow-hidden",
  cardHeader: "p-4 flex items-center justify-between",
  cardTitle: "text-sm font-bold text-[var(--color-fg)]",
  profileInfo: "flex items-center gap-3 p-4",
  profileName: "text-sm font-bold text-[var(--color-fg)] line-clamp-1",
  profileLink: "text-xs font-semibold text-accent hover:underline cursor-pointer",
  actionBtn: "w-full mt-4 bg-accent text-white rounded-xl py-2.5 text-sm font-bold transition-all hover:brightness-110 active:scale-[0.98] shadow-sm shadow-accent/20",
  helpInner: "m-1 rounded-xl p-4 border border-accent/10 bg-accent/5 transition-all duration-300",
  helpTitle: "text-sm font-bold text-[var(--color-fg)]",
  helpDesc: "text-xs mt-1 text-[var(--color-fg)]/60 leading-relaxed",
  helpBtn: "w-full mt-4 flex items-center justify-center gap-2 rounded-xl border border-accent/20 bg-[var(--color-surface)] py-2.5 text-xs font-bold text-accent transition-all hover:bg-accent hover:text-white active:scale-[0.98] shadow-sm shadow-accent/5",
  listItem: "flex items-center justify-between p-4 border-t border-[var(--color-border)] hover:bg-[var(--color-fg)]/5 transition-all cursor-pointer first:border-0",
  listItemLabel: "text-sm font-medium text-[var(--color-fg)] opacity-80",
  listItemIcon: "h-5 w-5 text-[var(--color-fg)] opacity-50",
  listItemArrow: "h-4 w-4 text-[var(--color-fg)] opacity-30",
};
