export const profilePageStyles = {
  card: "rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] shadow-sm overflow-hidden",
  banner: "h-32 bg-gradient-to-r from-accent via-purple-500 to-pink-500",
  avatarSection: "flex flex-col sm:flex-row items-center sm:items-end gap-4 px-6 -mt-12 pb-6",
  avatarContainer: "relative group cursor-pointer",
  avatar: "h-24 w-24 rounded-full object-cover border-4 border-[var(--color-surface)] shadow-lg transition-all group-hover:opacity-75",
  avatarOverlay: "absolute inset-0 flex items-center justify-center rounded-full bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity",
  editIcon: "text-white text-xl",
  name: "text-xl font-bold text-[var(--color-fg)] text-center sm:text-left",
  email: "text-sm text-[var(--color-fg)] opacity-60 text-center sm:text-left",
  roleBadge: "text-[10px] font-black uppercase tracking-widest text-accent bg-accent/10 px-2.5 py-0.5 rounded-full",
  subscriptionBadge: "text-[10px] font-black uppercase tracking-widest text-emerald-500 bg-emerald-500/10 px-2.5 py-0.5 rounded-full",
  sectionTitle: "text-base font-bold text-[var(--color-fg)]",
  tabsContainer: "flex items-center gap-1 border-b border-[var(--color-border)] px-4 bg-[var(--color-surface)] sticky top-0 z-10",
  tabButton: "relative px-4 py-4 text-sm font-medium transition-all duration-200 hover:text-accent outline-none",
  activeTab: "text-accent border-b-2 border-accent font-bold",
  inactiveTab: "text-[var(--color-fg)] opacity-50 hover:opacity-100",
  tabBadge: "ml-2 px-1.5 py-0.5 text-[10px] bg-[var(--color-border)] rounded-md font-bold",
};
